export const ORDER_ACTION_TYPES = {
  FETCH_ORDER: 'FETCH_ORDER',
  INSERT_ORDER_LINE: 'INSERT_ORDER_LINE',
  UPDATE_ORDER_LINE: 'UPDATE_ORDER_LINE',
  OPEN_ADD_MODAL: 'OPEN_ADD_MODAL',
  CLOSE_ADD_MODAL: 'CLOSE_ADD_MODAL',
  OPEN_EDIT_MODAL: 'OPEN_EDIT_MODAL',
  CLOSE_EDIT_MODAL: 'CLOSE_EDIT_MODAL',
};
