export const PRODUCT_ACTION_TYPES = {
  PRODUCT_ADD_QUANTITY: 'PRODUCT_ADD_QUANTITY',
  PRODUCT_SUBTRACT_QUANTITY: 'PRODUCT_SUBTRACT_QUANTITY',
  PRODUCT_UPDATE_CATEGORY: 'PRODUCT_UPDATE_CATEGORY',
  PRODUCT_UPDATE_SEARCH: 'PRODUCT_UPDATE_SEARCH',
  PRODUCT_SEARCH: 'PRODUCT_SEARCH',
};
